---
apiVersion: v1
kind: Namespace
metadata:
  name: ctse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-management-deployment
  namespace: ctse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-management
  template:
    metadata:
      labels:
        app: payment-management
    spec:
      containers:
        - name: payment-management
          image: it19170244/payment-management:latest
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: payment-management-config
---

