apiVersion: v1
kind: Service
metadata:
  namespace: ctse
  name: payment-management-service
spec:
  selector:
    app: payment-management
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: LoadBalancer
  publishNotReadyAddresses: true
